[technote]
id = "RTN-108"
series_id = "RTN"
canonical_url = "https://rtn-108.lsst.io"
github_url = "https://github.com/lsst/rtn-108"
github_default_branch = "main"
date_created = 2025-10-17T20:50:05Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Katherine"
name.family = "Laliotis"
internal_id = "laliotisk"
orcid = "https://orcid.org/0000-0002-6111-6061"
[[technote.authors.affiliations]]
name = "The Ohio State University"
internal_id = "OSU"
address = "Columbus"
